plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

repositories {
    maven { url "https://maven.nucleoid.xyz" }
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "${mod_id}.refmap.json"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modCompileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modCompileOnly "eu.pb4:sgui:${sgui_version}"
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    // SnakeYAML 仅用于编译，运行时由 fabric 子项目通过 include 打包
    compileOnly 'org.yaml:snakeyaml:2.2'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
